### ISSUE TITLE
Ig secret having unrendered variables

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry-incubator/quarks-operator#987] opened 2020-06-17 07:54 UTC
Issue mentioned in KubeCF repo - https://github.com/cloudfoundry-incubator/kubecf/issues/973

**Comment by jandubois** [comment] 2020-06-30 19:46
Isn't this a duplicate of #750?

**Comment by rohitsakala** [comment] 2020-07-06 05:44
> Isn't this a duplicate of #750?

No, this issue is related to ig secrets having explicit variables not being rendered as Mark has pointed out.

**Comment by rohitsakala** [comment] 2020-07-10 07:27
Hi @mook-as ,

This issue should be fixed with these PR's - https://github.com/cloudfoundry-incubator/quarks-operator/pull/1013. I checked on latest cf-operator and kubecf v2.2.0.

**Closed** 2020-07-10 07:28 UTC
Labels: bug, in progress
