### ISSUE TITLE
Pod from BOSH deployment disappearing after initial rollout

### ISSUE THREAD

**Issue by mudler** [cloudfoundry-incubator/quarks-operator#1137] opened 2020-09-23 12:37 UTC
**Describe the bug**

After deploying KubeCF with Eirini, the deployment comes up, but right after it is completely rolled out, it disappears - all pods are being deleted and qsts gets deleted as well.

The screenshots are about another deployment, I managed to get the [quarks-* component logs](https://github.com/cloudfoundry-incubator/quarks-operator/files/5268097/cfo.log) in another run

[kubelogs.tar.gz](https://github.com/cloudfoundry-incubator/quarks-operator/files/5268179/kubelogs.tar.gz)

![Screenshot_20200922_153042](https://user-images.githubusercontent.com/2420543/94013116-eadeed00-fda9-11ea-8149-de45071f375b.png)
![Screenshot_20200922_153150](https://user-images.githubusercontent.com/2420543/94013157-f6321880-fda9-11ea-9338-bac74b6c4e91.png)

Sometimes, it did happened also to see no pod being started at all after the ig job is done.

This doesn't seems to happen with cfo 5.2.0, so the changes that introduces this bug must be between these: https://github.com/cloudfoundry-incubator/quarks-operator/compare/v5.2.0...v6.0.0

As @jimmykarily pointed out, this could be caused by https://github.com/kubernetes/kubernetes/issues/88097

Update:
Bug shows also with cfo `6.0.0%2B0.g15238d6d`

**To Reproduce**

Try to deploy KubeCF with Eirini more than one time, occasionally in a slow deployment the situation should re-occour

**Expected behavior**
KubeCF to stay alive :man_dancing:  

**Environment**
 - cfcontainerization/cf-operator:v6.1.0-0.g5451299e
 - kind

**Comment by manno** [comment] 2020-09-24 09:23
I can repro this and I see similar lines in
[kube-controller-manager-logs.tar.gz](https://github.com/cloudfoundry-incubator/quarks-operator/files/5274829/kube-controller-manager-logs.tar.gz).

**Comment by rohitsakala** [comment] 2020-09-24 13:51
I can reproduce this on Kube v1.16.4 too. Trying to reproduce by removing the PR related to `Replace dm job with withops controller"

**Comment by manno** [comment] 2020-09-24 14:13
The problem doesn't happen with a small deployment (docs/examples/bosh-deployment/boshdeployment-with-custom-variable.yaml). However after kubecf failed, I  could trigger the same error on  the same cluster, by deploying the small deployment and shelling into the kube-controller-manager-kind-control-plane and running `kill -15 1`.

**Comment by mudler** [comment] 2020-09-24 14:58
Attaching more logs, obtained with kind and a more verbose configuration: 
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    controllerManager:
      extraArgs:
        v: "5"
```

[cfologs.txt](https://github.com/cloudfoundry-incubator/quarks-operator/files/5277017/cfologs.txt)

[kind.tar.gz](https://github.com/cloudfoundry-incubator/quarks-operator/files/5277026/kind.tar.gz)

Note, during deployment I had to kill the ig pod because it was stuck in  ContainerCreating (I had 2 ig jobs) but then it ended successfully with a deployment - which was teared down after ~15mins

**Comment by manno** [comment] 2020-09-24 16:02
Upgrading dependencies (controller-runtime v0.6.0 to v0.6.3) didn't help.

**Comment by jimmykarily** [comment] 2020-09-25 06:06
Copying information here from Slack conversation.

In Ettores `kind.tar.gz` above, the action starts around line 4678 in file 4.log in dir ` kube-system_kube-controller-manager-kubecf-control-plane_be2ccc90374c3aecc2ee17ad987a94f7`.

there is this log line:

```
2020-09-24T14:52:11.888441035Z stderr F I0924 14:52:11.888247       1 garbagecollector.go:419] item [quarks.cloudfoundry.org/v1alpha1/QuarksJob, namespace: kubecf, name: kubecf, uid: bb2bd707-105c-455d-9bee-37f0c6dadddb] not found, generating a virtual delete event
```

which seems like GC is trying to delete a QuarksJob with uid: `bb2bd707-105c-455d-9bee-37f0c6dadddb`

That uid though, is obviously the uid of the BOSHDeployment, as seen in lines like this one (all over the logs):

```
2020-09-24T14:52:11.538077728Z stderr F I0924 14:52:11.537898       1 garbagecollector.go:459] object garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"quarks.cloudfoundry.org/v1alpha1", Kind:"QuarksSecret", Name:"var-router-ssl", UID:"a0c54484-048d-4c4a-af72-a8c36ccee524", Controller:(*bool)(0xc00070604c), BlockOwnerDeletion:(*bool)(0xc00070604d)}, Namespace:"kubecf"} has at least one existing owner: []v1.OwnerReference{v1.OwnerReference{APIVersion:"quarks.cloudfoundry.org/v1alpha1", Kind:"BOSHDeployment", Name:"kubecf", UID:"bb2bd707-105c-455d-9bee-37f0c6dadddb", Controller:(*bool)(0xc002604896), BlockOwnerDeletion:(*bool)(0xc002604897)}}, will not garbage collect
```

Since it can't find a QuarksJob with that uid, it decides it has to delete it:

```
2020-09-24T14:52:11.888573914Z stderr F I0924 14:52:11.888473       1 graph_builder.go:543] GraphBuilder process object: /, namespace kubecf, name kubecf, uid bb2bd707-105c-455d-9bee-37f0c6dadddb, event type delete
```

and after that it becomes a mess. I probably marks that uid for deletion which means it starts deleting dependants of that uid. But the dependants of that uid (actually of the BOSHDeployment, not the false QuarksJob) are the Qsts and QSecrets  so they get deleted.

What I think happens it we falsely create and owner reference with type QuarksJob and the uid of the BOSHDeployment and the GC keeps track of various object using just uids (although in it seems that when doing a look up it's also using the type).

**Comment by jimmykarily** [comment] 2020-09-25 06:56
I think this is the problem:

- This is hard-coded to QuarksJob: https://github.com/cloudfoundry-incubator/quarks-utils/blob/master/pkg/versionedsecretstore/versioned_secret_store.go#L241
- The caller passes the uid of a boshdeployment: https://github.com/cloudfoundry-incubator/quarks-operator/blob/master/pkg/kube/controllers/boshdeployment/withops_reconciler.go#L192

**Comment by manno** [comment] 2020-09-29 07:57
I think this was fixed byhttps://github.com/cloudfoundry-incubator/quarks-operator/pull/1139

**Closed** 2020-09-29 08:01 UTC
Labels: bug, delivered
